@echo off
setlocal

echo ========================================
echo   Master Chess - CONSERVATIVE RESET
echo ========================================
echo.

set "AGGRESSIVE_FUTURES_BURST=false"
set "FORCE_MODEL_RETRAIN_ON_START=false"
set "TRADE_CYCLE_INTERVAL_OVERRIDE="
set "MODEL_RETRAIN_HOURS_OVERRIDE="
set "MIN_ML_CONFIDENCE_OVERRIDE="
set "MIN_ENSEMBLE_SCORE_OVERRIDE="
set "MAX_CORRELATION_OVERRIDE="
set "MAX_POSITIONS_SPOT_OVERRIDE="
set "MAX_POSITIONS_FUTURES_OVERRIDE="
set "CB_MAX_CONSECUTIVE_LOSSES_OVERRIDE="
set "CB_DAILY_LOSS_LIMIT_PCT_OVERRIDE="
set "CB_MAX_DRAWDOWN_PCT_OVERRIDE="

set "ENABLE_FUTURES=true"
set "ENABLE_COINBASE_FUTURES_DATA=true"
set "ENABLE_KRAKEN_FUTURES_FALLBACK=true"
set "DIRECTION_BIAS=short_lean"
set "DIRECTION_BIAS_STRENGTH=0.06"
set "RL_SHADOW_MODE=true"
set "RL_LIVE_SIZE_CONTROL=false"
set "RL_LIVE_SIZE_MIN_MULT=0.5"
set "RL_LIVE_SIZE_MAX_MULT=1.5"
set "USE_LOCKED_PROFILE=true"

echo Burst mode: %AGGRESSIVE_FUTURES_BURST%
echo Force retrain: %FORCE_MODEL_RETRAIN_ON_START%
echo RL live size: %RL_LIVE_SIZE_CONTROL% (%RL_LIVE_SIZE_MIN_MULT%x-%RL_LIVE_SIZE_MAX_MULT%x)
echo.

call "C:\Master Chess\START_BOT.bat"

endlocal
