import urllib.request, json
d = json.loads(urllib.request.urlopen('http://127.0.0.1:8088/api/all', timeout=10).read())
# Account
a = d.get('account', {})
print("=" * 60)
print("ACCOUNT OVERVIEW")
print("=" * 60)
print(f"  Equity:        ")
print(f"  Cash:          ")
print(f"  Buying Power:  ")
print(f"  Status:        {a.get('status','?')}")
# PutSeller
ps = d.get('putseller', {})
print()
print("=" * 60)
print("PUTSELLER (Iron Condor)")
print("=" * 60)
print(f"  Status:         {ps.get('status','?')}")
print(f"  Position Count: {ps.get('position_count',0)} ({ps.get('call_count',0)} calls, {ps.get('put_count',0)} puts)")
print(f"  Total Credit:   ")
print(f"  Total Risk:     ")
print(f"  Unrealized PnL: ")
print(f"  Closed Trades:  {ps.get('total_trades',0)}")
print(f"  Wins/Losses:    {ps.get('wins',0)}/{ps.get('losses',0)} ({ps.get('win_rate',0):.1f}%)")
bal = ps.get('balances', {})
print(f"  Balance:        ")
print(f"  Realized PnL:   ")
# Per-position summary
positions = ps.get('positions', [])
print(f"\n  --- Open Positions ({len(positions)}) ---")
winners = sum(1 for p in positions if p.get('current_pnl',0) > 0)
losers = sum(1 for p in positions if p.get('current_pnl',0) < 0)
flat = sum(1 for p in positions if p.get('current_pnl',0) == 0)
total_pnl = sum(p.get('current_pnl',0) for p in positions)
worst = min(positions, key=lambda p: p.get('current_pnl_pct',0)) if positions else {}
best = max(positions, key=lambda p: p.get('current_pnl_pct',0)) if positions else {}
print(f"  Green/Red/Flat:  {winners}/{losers}/{flat}")
print(f"  Net Unrealized:  ")
if worst:
    print(f"  Worst position:  {worst['underlying']} {worst['spread_type']}  ({worst.get('current_pnl_pct',0):+.1f}%)")
if best:
    print(f"  Best position:   {best['underlying']} {best['spread_type']}  ({best.get('current_pnl_pct',0):+.1f}%)")
# Risk utilization
equity = float(a.get('equity', 100000))
risk_util = (ps.get('total_risk',0) / equity) * 100
print(f"  Risk / Equity:   {risk_util:.1f}%")
# CallBuyer
cb = d.get('callbuyer', {})
print()
print("=" * 60)
print("CALLBUYER")
print("=" * 60)
print(f"  Status:         {cb.get('status','?')}")
print(f"  Positions:      {cb.get('position_count',0)}")
print(f"  Closed Trades:  {cb.get('total_trades',0)}")
print(f"  Unrealized PnL: ")
print(f"  ML Warmup:      {cb.get('ml_status','?')}")
print(f"  Meta Status:    {cb.get('meta_status','?')}")
# Crypto
cr = d.get('crypto', {})
print()
print("=" * 60)
print("CRYPTOBOT")
print("=" * 60)
print(f"  Status:         {cr.get('status','?')}")
spot = cr.get('spot', {})
fut = cr.get('futures', {})
print(f"  Spot Balance:    (PnL: )")
print(f"  Futures Bal:     (PnL: )")
print(f"  Open Positions: {cr.get('open_positions',0)}")
print(f"  Trades (24h):   {cr.get('trades_24h','?')}")
# AlpacaBot
ab = d.get('alpaca', {})
print()
print("=" * 60)
print("ALPACABOT (Dormant)")
print("=" * 60)
print(f"  Status:         {ab.get('status','?')}")
print(f"  Allocation:     {ab.get('allocation_pct',0)*100:.0f}%")
# Guardrails
g = d.get('guardrails', {})
print()
print("=" * 60)
print("GUARDRAILS")
print("=" * 60)
print(f"  Total Risk:     ")
print(f"  Risk %:         {g.get('risk_pct',0):.1f}%")
print(f"  Warnings:       {g.get('warnings', [])}")
